# Generated by Django 5.2.17 on 2026-08-31 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_-]*$', 'Identifiant de module invalide (attendu : slug minuscule).')])),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+\\.\\d+\\.\\d+$', 'Version invalide (format attendu : MAJOR.MINOR.PATCH).')])),
                ('state', models.CharField(choices=[('installed', 'Installé'), ('activated', 'Activé'), ('deactivated', 'Désactivé')], max_length=20)),
                ('manifest_snapshot', models.JSONField()),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': '"core"."modules"',
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_constraint', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(>=|<=|==|~=|>|<)?\\d+\\.\\d+\\.\\d+$', 'Contrainte de version invalide (ex. ">=1.0.0").')])),
                ('depends_on_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core.module')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.module')),
            ],
            options={
                'verbose_name': 'Dépendance de module',
                'verbose_name_plural': 'Dépendances de module',
                'db_table': '"core"."module_dependencies"',
                'constraints': [models.UniqueConstraint(fields=('module', 'depends_on_module'), name='uniq_module_dependency')],
            },
        ),
    ]
