# Generated by Django 5.2.17 on 2026-08-31 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_moduledependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.user')),
            ],
            options={
                'verbose_name': "Entrée de journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': '"core"."audit_log"',
            },
        ),
    ]
