# Generated by Django 5.2.17 on 2026-08-31 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec'), ('refused', 'Refusé')], max_length=20)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Exécution de sauvegarde',
                'verbose_name_plural': 'Exécutions de sauvegarde',
                'db_table': '"core"."backup_runs"',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.user'),
        ),
    ]
