# Generated by Django 5.2.17 on 2026-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('terminated', 'Rompu')], default='active', max_length=20),
        ),
    ]
