# Generated by Django 5.2.17 on 2026-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approver_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
